from enum import Enum

class AuditAction(str, Enum):

    # ===== AUTH =====
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"

    # ===== USER =====
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    USER_PASSWORD_UPDATE = "USER_PASSWORD_UPDATE"

    # ===== SUPPLIER =====
    SUPPLIER_CREATE = "SUPPLIER_CREATE"
    SUPPLIER_UPDATE = "SUPPLIER_UPDATE"
    SUPPLIER_LEADTIME_UPDATE = "SUPPLIER_LEADTIME_UPDATE"
    SUPPLIER_DELETE = "SUPPLIER_DELETE"

    # ===== ORDER =====
    ORDER_CREATE = "ORDER_CREATE"
    ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE"

    # ===== DEMAND =====
    DEMAND_UPDATE = "DEMAND_UPDATE"

    # ===== IMPORT =====
    IMPORT_SUCCESS = "IMPORT_SUCCESS"
    IMPORT_FAILURE = "IMPORT_FAILURE"
    IMPORT_ROW_FAILURE = "IMPORT_ROW_FAILURE"

    # ===== SYSTEM =====
    SYSTEM_ERROR = "SYSTEM_ERROR"